# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        user:
            entity:
                  class: AppBundle\Entity\User
                  property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: user
            anonymous: ~
            form_login:
              login_path: login
              check_path: login
              default_target_path: index
            logout:
              path: logout
              target: login
    access_control:
        # l'ordre des accès est IMPORTANT !
        - { path: ^/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
    access_denied_url: /login
